### ISSUE TITLE
Add new actions for testing

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#919]
We should have the following new/modified actions:
- [ ] one generic action to set up AMUSE, which other actions can then use (avoiding duplication)
- [ ] a test using this to test framework (perhaps as part of the above), using the current 'inplace' action as a template
- [ ] actions that build and test a specific community code, triggering on a change in the community code dir:
```
name: test-{codename}

on:
  push:
    paths:
      - src/amuse/community/{codename}
```
- [ ] these could then (maybe) also build new packages and upload to PyPI

This should allow for much better testing than we currently have, and should allow us to automatically approve PRs and build packages if everything is successful
